version: '3.8'

services:
  dz_sales_intel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dz_sales_intel
    restart: "no"
    env_file:
      - .env
    environment:
      - TZ=Africa/Algiers
    volumes:
      - ./data:/app/data
      - ./logs:/app/data/logs
    ports:
      - "8080:8080"
    mem_limit: 512m
    cpus: "1.0"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
